<template>
	<view class="cu-list menu sm-border card-menu margin-tb-sm bg-white">
		<view class="text-center text-xl margin-top-xs">{{ checkedDate }}</view>
		<view v-if="checkedDay==''" class="text-center">
			<image style="height: 200rpx;" src="https://r2.airmole.cn/i/2025/05/02/%E7%82%92%E9%A5%AD.gif"
				mode="heightFix"></image>
			<view class="text-xl margin-tb-sm">数据待更新</view>
		</view>
		<view v-else class="padding-lr-xs padding-bottom-sm">
			<view class="margin-tb-xs">
				<view class="cu-capsule radius">
				    <view class='cu-tag bg-blue'>天气</view>
				    <view class="cu-tag line-bliue">{{checkedDay.weather}}</view>
				</view>
				<view v-if="checkedDay.wind" class="cu-capsule radius margin-lr-xs">
					<view class='cu-tag bg-blue'>风力</view>
					<view class="cu-tag line-bliue">{{checkedDay.wind}}</view>
				</view>
				<view v-if="checkedDay.weekday" class="cu-tag line-blue radius margin-lr-xs">{{checkedDay.weekday}}</view>
				<view v-if="checkedDay.info && checkedDay.info !== '　'" class="cu-tag radius line-blue margin-lr-xs">{{checkedDay.info}}</view>
				<view v-if="checkedDay.event" class="cu-tag line-blue radius margin-lr-xs">{{checkedDay.event}}</view>
			</view>
			<view class="margin-tb-xs"><hr /></view>
			<view class="flex text-center border">
				<view class="flex-sub padding-xs border"><span class="text-blue">{{ checkedDay.month }}</span>月<span
						class="text-blue">{{ checkedDay.day }}</span>日</view>
				<view class="flex-sub padding-xs border">星期：<span class="text-blue">{{ checkedDay.weekday[2] }}</span>
				</view>
				<view class="flex-sub padding-xs border">天气：<span class="text-blue">{{ checkedDay.weather }}</span>
				</view>
			</view>
			<view class="flex text-left border">
				<view class="flex-sub padding-xs">巡查地点：</view>
			</view>
			<view class="flex text-left border">
				<view class="flex-sub padding-xs">
					<text>巡查结果：</text>
					<view style="text-indent: 2em;">
						<text v-if="error" class="text-red">{{ error }}</text>
						<text v-else-if="!typedLog" class="text-red">正在生成中...</text>
						<text v-else :decode="true">{{ typedLog }}</text>
					</view>
				</view>
			</view>
			<view class="flex border">
				<view class="flex-sub padding-xs border text-left">站长签字：</view>
				<view class="flex-sub padding-xs border text-left">护林员：</view>
			</view>

			<view class="margin-top-xl">
				<view class="text-center text-orange">巡护日志由讯飞星火AI大模型生成</view>
				<view class="text-center text-orange">请注意自行判断是否符合实际情况可用！</view>
				
				<view class="flex justify-center margin-top-sm">
					<button class="cu-btn sm round bg-blue shadow" @click="generateGuardLog" :disabled="generating">
						<text class="cuIcon cuIcon-refresh margin-right-xs"></text> {{ generating ? '生成中...' : '重新生成' }}
					</button>
				</view>
			</view>
		</view>
	</view>
</template>

<script setup>
	import {
		ref,
		defineProps,
		onMounted,
		watch
	} from 'vue';

	// 定义props
	const props = defineProps({
		checkedDate: String,
		checkedDay: [String, Object]
	});

	const guardLog = ref('');
	const typedLog = ref('');
	const currentIndex = ref(0);
	const typingInterval = ref(null);

	const startTyping = () => {
		if (typingInterval.value) clearInterval(typingInterval.value);
		currentIndex.value = 0;
		typedLog.value = '';
		
		typingInterval.value = setInterval(() => {
			if (currentIndex.value < guardLog.value.length) {
				typedLog.value += guardLog.value.charAt(currentIndex.value);
				currentIndex.value++;
			} else {
				clearInterval(typingInterval.value);
			}
		}, 50);
	};

	watch(guardLog, () => {
		startTyping();
	});
	const generating = ref(false);
	const error = ref('');
	const substituteName = ref('');
	const autoGenerated = ref(false);

	// 监听日期变化，清空生成的日志和错误信息
	watch(() => [props.checkedDate, props.checkedDay], () => {
		guardLog.value = '';
		typedLog.value = '';
		error.value = '';
		autoGenerated.value = false;
	});

	// 获取代班同事姓名设置
	const getSubstituteName = async () => {
		try {
			const setting = await uni.getStorage({
				key: 'setting'
			});
			if (setting.data && setting.data.partner) {
				substituteName.value = setting.data.partner;
			}
		} catch (error) {
			console.log('未找到代班同事设置');
		}
	};

	// 监听设置更新事件
	uni.$on('settingUpdated', getSubstituteName);

	onMounted(() => {
		getSubstituteName();
	});

	// 暴露自动生成方法给父组件
	defineExpose({
		autoGenerateLog
	});

	/**
	 * 自动生成护林员日志
	 */
	function autoGenerateLog() {
		if (autoGenerated.value || !props.checkedDay || typeof props.checkedDay === 'string') {
			return;
		}
		generateGuardLog();
		autoGenerated.value = true;
	}

	/**
	 * 生成护林员日志
	 */
	async function generateGuardLog() {
		if (!props.checkedDay || typeof props.checkedDay === 'string') {
			error.value = '请先选择有效的日期';
			return;
		}

		console.log(props.checkedDay)

		guardLog.value = '';
		typedLog.value = '';
		error.value = '';
		generating.value = true;

		const params = new URLSearchParams();
		params.append('date', props.checkedDate);
		params.append('weather', props.checkedDay.weather || '');
		params.append('wind', props.checkedDay.wind || '');
		params.append('isMeeting', props.checkedDay.info.includes('护林例会') ? 'true' : 'false');
		params.append('isHoliday', props.checkedDay.info.includes('休假') ? 'true' : 'false');
		params.append('substituteName', substituteName.value || '');
		params.append('isSubstitute', props.checkedDay.info.includes('代班') ? 'true' : 'false');
		params.append('keywords', props.checkedDay.event || '');

		const apiUrl = `/api/ailog?${params.toString()}`;

		try {
			const response = await fetch(apiUrl);
			const data = await response.json();

			if (data.status === 'success' && data.log) {
				guardLog.value = data.log;
			} else if (data.status === 'error' && data.error) {
				// 展示讯飞星火返回的详细错误信息
				let errorMsg = data.error;
				if (data.errorCode) {
					errorMsg = `${errorMsg}（错误码: ${data.errorCode}）`;
				}
				error.value = errorMsg;
			} else {
				error.value = '生成日志失败，返回数据格式错误';
			}
		} catch (e) {
			error.value = '生成日志失败，请检查网络连接后重试';
			console.error('请求API失败:', e);
		} finally {
			generating.value = false;
		}
	}
</script>

<style>
	.border {
		border: 1px solid #e5e5e5;
	}
</style>
